package thick.tagger;

public class ThickTags {
	public static String[] names = {
		"registrar",
		"domain",
		"registrant",
		"date",
		"other"
	};
	
	public static String[][] keys = {
		{
			"Server",
			"Registrar WHOIS",
			"Reseller URL",
			"Registrar-URL",
			"Registered through",
			"registrar",
			"Registrar WhOIS Server",
			"Registrar Whois",
			"ReferralServer",
			"Registrar",
			"Registered via",
			"Registrar Name",
			"Registrar Domain ID",
			"Registrar WHOIS Server",
			"Reseller",
			"Whois Server",
			"Registrar WHOIS server",
			"Registrar Abuse Contact Phone",
			"Whois server",
			"REGISTRARNAME",
			"Registrar Abuse Email",
			"Sponsoring Registrar",
			"Registrar Homepage",
			"Registered-By",
			"Registrar Whois Server",
			"Reseller Site",
			"Registrar IANA ID",
			"Registration service provided by",
			"Domain Maintainer",
			"Registrar Abuse Phone",
			"Registrar Abuse Contact Email",
			"Sponsoring Registrar IANA ID",
			"Registrar URL",
			"WHOIS Server",
			//"Registrars.Registration Service Provided By",
			"Registrar of Record",
			"registrar_IANA_id",
			"Referral URL",
			"Reseller Email",
		},
		{
			"Domain nameservers",
			"Status",
			"version",
			"domain",
			"Nameservers",
			"query_status",
			"Domain Name Servers in listed order",
			"NameServer",
			"Fifth Nameserver",
			"nameserver",
			"This domain is delegated to DynECT Managed DNS",
			"Name Server",
			"Whoisprivacy",
			"Domains Status",
			"Registry Domain ID",
			"Domain Information",
			"nameserver4",
			"nameserver2",
			"nameserver3",
			"nameserver1",
			"status",
			"Status(es",
			"Primary Name Server",
			"Nameserver",
			"Fourth Nameserver",
			"ns",
			"Domain name servers in listed order",
			"Secondary Name Server",
			"Domain idn name",
			"Domain Servers",
			"Second Nameserver",
			"This domain is delegated to Dyn Standard DNS",
			"Name Servers",
			"Domain name",
			"Name servers",
			"Domain Name servers(es",
			"Domain Name",
			"Domain servers in listed order",
			"Domain servers",
			"First Nameserver",
			"PunyCode",
			"Domain",
			"Domain Nameservers in listed order",
			"Domain Name Servers",
			"Domain status",
			"DNSSEC",
			"DNSSec",
			"domain_name",
			"Domain Status",
			"Name server",
			"Domain Registration Parther Website",
			"Host Name",
			"Domain Registration Partner",
			"Third Nameserver",
			"Domain ID",
			"NAMESERVER",
			"DOMAINNAME",
			"query_datetime",
			"This domain is using Dyn Parking Service",
		},
		{
			"REGISTRANT Street",
			"Registrant Name",
			"REGISTRANTFAX",
			"Registrant Phone",
			"registrant",
			"Organization PC",
			"Organization State",
			"Organization City",
			"Registrant Contact Information",
			"Registry Registrant ID",
			"registrant_contact_fax",
			"REGISTRANT Phone Ext",
			"REGISTRANTPOSTALCODE",
			"REGISTRANT Postal Code",
			"REGISTRANT Fax",
			"REGISTRANTCOUNTRY",
			"Registrant State/Province",
			"registrant_contact_phone",
			"registrant_contact_address1",
			"REGISTRANT Organization",
			"Owner CountryID",
			"Owner Name",
			"Registrant State / Province",
			"Registrant Address",
			"Registrant-Email",
			"registrant_contact_email",
			"Registrant ID",
			"owner",
			"Registrant Phone Ext",
			"Registrant-City",
			"REGISTRANTPHONE",
			"Registrant Phone EXT",
			"Registrant E-mail",
			"Registrant Orginization",
			"Registrant-Street1",
			"Registrant-Street2",
			"Organization Contact Id",
			"Registrant State",
			"Organization Name",
			"Registrant Details",
			"REGISTRANT Phone",
			"REGISTRANTLASTNAME",
			"REGISTRANTSTATE",
			"Registry Registrant Registrant ID",
			"Registrant Firstname",
			"REGISTRANT Fax Ext",
			"Register Street",
			"Registrant Contact Details",
			"Registrant FAX Ext",
			"Organization e-mail",
			"REGISTRANTORGANIZATION",
			"REGISTRANTADDRESS3",
			"REGISTRANTADDRESS1",
			"REGISTRANTADDRESS2",
			"REGISTRANT Name",
			"Registrant-Country",
			"registrant_contact_city",
			"Registrant Province/state",
			"Registrant Phone Number",
			"Registrant Fax Ext",
			"Registrant Fax EXT",
			"Registrant-Phone",
			"OWNER",
			"Organization Fax",
			"Registrant Country",
			"REGISTRANTCITY",
			"Owner Phone",
			"Registrant Address Line 2",
			"Registrant Address Line 1",
			"Registrant-Fax",
			"Registrant Organisation",
			"Registrant-Zip",
			"Registry REGISTRANT ID",
			"Registrant contact",
			"Registrant Postal Code",
			"holder",
			"Owner City",
			"Registrant Fax",
			"Registrant FAX",
			"Registant",
			"REGISTRANT State/Province",
			"Owner Address2",
			"Owner Address1",
			"REGISTRANT Country",
			"Registrant Street",
			"Organization Phone",
			"REGISTRANTFIRSTNAME",
			"registrant_contact_name",
			"registrant_contact_country",
			"Organization Street",
			"Owner Country",
			"Organization Org",
			"Registrant Organization",
			"registrant_contact_province",
			"Registrant Email",
			"registrant_contact_organization",
			"Registrant Lastname",
			"Registrant-State",
			"Owner email",
			"REGISTRANT City",
			"Registrant City",
			"Registrant PCode",
			"Organization Country",
			"REGISTRANTEMAIL",
			"Registrant Contact",
			"Owner State",
			"Registrant Country Code",
			"Owner Zip",
			"Owner Fax",
			"registrant_contact_postalcode",
			"Registrant",
			"Registrant Fax Number",
			"REGISTRANT Email",
			"Registrant Address1",
			"Registrant-Name",
			"Registrant-Organization",
			"Registrant Street1",
			"Registrant Street3",
			"Registrant Street2",
			"Registrant Info",
			"Owner-c",
			"Registrant Province/State",
		},
		{
			"Record last updated",
			"Domain Expires",
			"Last updated Date",
			"REGISTERDATE",
			"Expiration date",
			"domain_datebilleduntil",
			"registration_date",
			"Expiration Date",
			"Last updated",
			"Domain Registration Date",
			"Update Date",
			"Valid Date",
			"Last Update",
			"Update date",
			"LASTMODIFIEDDATE",
			"Record Created on",
			"modified",
			"domain_dateregistered",
			"Updated",
			"Registration Date",
			"Expire",
			"registered_date",
			"Modified",
			"registered",
			"Updated date",
			"Last Updated On",
			"Create Date",
			"Created On",
			"Creation-Date",
			"Expiry Date",
			"Expire on",
			"Expires",
			"Updated Date",
			"Registrar Registration Expiration Date",
			"Record created",
			"Created",
			"Domain Expiration Date",
			"Last Updated Date",
			"Registrar Registration Expiration date",
			"Last Updated on",
			"EXPIREDATE",
			"expiration_date",
			"Registered Date",
			"Registrar Registration Expiration",
			"Registry Expiry Date",
			"changed",
			"expires",
			"Creation date",
			"Last Update Date",
			"Creation Date",
			"Expiration-Date",
			"Created Date",
			"Registrar Expiration Date",
			"Record expires",
			"created",
			"Created date",
			"Domain Last Updated Date",
			"registerexpire_date",
		},
		{
			"ADMINADDRESS3",
			"ADMINADDRESS2",
			"ADMINADDRESS1",
			"Tech-Name",
			"Administrative Organization",
			"technical_contact_country",
			"Tech-Fax",
			"Tech-Zip",
			"Administrative Fax",
			"Administrative Fax Ext",
			"Registry Technical ID",
			"technical_contact_email",
			"Technical Fax",
			"Billing Name",
			"Administrative contact, Billing_contact, Technical contact, Zone contact",
			"Tech Orginization",
			"Technical contact",
			"Tech Contact",
			"BILLINGFAX",
			"Administrative Contact Information",
			"Billing Postal Code",
			"Tech CountryID",
			"Administrative Country",
			"Administrative contact",
			"admin_contact_email",
			"Tech Address Line 1",
			"Admin Phone",
			"Tech Address Line 2",
			"TECHORGANIZATION",
			"Billing Province/State",
			"Billing Phone",
			"Tech Phone",
			"ADMINORGANIZATION",
			"ADMINPOSTALCODE",
			"BILLINGFIRSTNAME",
			"Technical E-mail",
			"Tech Postal Code",
			"ADMIN",
			"Billing Phone Ext",
			"Tech email",
			"Billing Phone EXT",
			"BILLINGSTATE",
			"Billing Country",
			"Technical Province/State",
			"TECHLASTNAME",
			"Technical Fax Ext",
			"Admin Name",
			"Administrative Contacts",
			"Admin Street3",
			"Admin Street2",
			"Admin Street1",
			"Technical ID",
			"Tech-Country",
			"Technical State",
			"Registry Admin ID",
			"Technical Org",
			"Technical Contact Details",
			"Admin-Organization",
			"Administrative Phone Ext",
			"Regestry Admin ID",
			"Tech-Email",
			"Tech-State",
			"Admin-Street1",
			"Admin-Street2",
			"Technical Email",
			"admin_contact_fax",
			"Billing Firstname",
			"Admin E-mail",
			"Admin Address1",
			"Admin",
			"Admin Address2",
			"Administrative Phone Number",
			"admin_contact_organization",
			"BILLINGPOSTALCODE",
			"Admin Province/state",
			"BILLINGCOUNTRY",
			"ADMINFIRSTNAME",
			"Admin Organisation",
			"Registry Admin Registrant ID",
			"admin_contact_address1",
			"Tech Phone Number",
			"Billing E-mail",
			"technical_contact_name",
			"Billing-c",
			"Technical Country Code",
			"technical_contact_phone",
			"Tech Country",
			"Tech contact",
			"Tech-City",
			"Administrative Province/State",
			"Administrative Street",
			"Billing Contacts",
			"admin_contact_postalcode",
			"technical_contact",
			"Admin State / Province",
			"BILLINGADDRESS3",
			"BILLINGADDRESS1",
			"BILLINGADDRESS2",
			"Tech State/Province",
			"Tech FAX Ext",
			"Billing City",
			"Technical Postal Code",
			"Administrative Contact",
			"Tech-Phone",
			"Administrative Postal Code",
			"Billing Fax Ext",
			"Billing Fax EXT",
			"Registry Tech ID",
			"Administrative Contact Id",
			"Technical Address",
			"Admin State/Province",
			"Administrative City",
			"technical_contact_organization",
			"Billing email",
			"Admin Country",
			"Technical Street",
			"Billing ID",
			"ADMINFAX",
			"ADMINCOUNTRY",
			"Admin-City",
			"Admin Organization",
			"Billing CountryID",
			"Billing State/Province",
			"Tech Firstname",
			"Billing State",
			"Administrative PC",
			"Tech Province/state",
			"ADMINSTATE",
			"ADMINPHONE",
			"Admin-Email",
			"Admin Contact",
			"admin_contact_country",
			"TECHPHONE",
			"Admin ID",
			"Tech PostalCode",
			"TECHFAX",
			"Tech E-mail",
			"BILLINGLASTNAME",
			"admin_contact_phone",
			"Admin State",
			"Technical PC",
			"Administrative e-mail",
			"Billing contact",
			"Admin email",
			"Billing Address2",
			"Billing Address1",
			"Tech Fax",
			"Tech FAX",
			"Tech Zip",
			"Admin Lastname",
			"admin_contact_name",
			"technical_contact_province",
			"Administrative Contact, Technical Contact",
			"Administrative Org",
			"BILLINGPHONE",
			"Tech-Street2",
			"Admin Phone Ext",
			"Admin Phone EXT",
			"Billing Country Code",
			"Tech-Street1",
			"Admin-c",
			"Admin FAX Ext",
			"Tech-c",
			"Tech City",
			"Tech State / Province",
			"Billing Fax Number",
			"Administrative State",
			"Admin Fax",
			"Admin FAX",
			"BILLINGORGANIZATION",
			"Admin Postal Code",
			"technical_contact_city",
			"Admin Zip",
			"Tech Street",
			"Admin contact",
			"Administrative",
			"Administrative Address",
			"administrative_contact",
			"Administrative Name",
			"Administrative Email",
			"Billing Email",
			"Technical Phone Ext",
			"Tech-Organization",
			"technical_contact_postalcode",
			"TECHSTATE",
			"ADMINCITY",
			"Technical Phone",
			"Billing Contact",
			"Administrative ID",
			"Tech",
			"Admin Address Line 1",
			"Admin Address Line 2",
			"Technical Phone Number",
			"Admin Fax Number",
			"Tech Organisation",
			"Tech State",
			"Admin-Phone",
			"tech",
			"Technical State/Province",
			"Admin-Country",
			"Registry Tech Registrant ID",
			"Admin Fax Ext",
			"Admin Fax EXT",
			"Admin Firstname",
			"Technical City",
			"Administrative Contact Details",
			"Admin Street",
			"admin",
			"admin_contact_city",
			"Tech Organization",
			"Technical e-mail",
			"Administrative, Billing Contact",
			"Tech Email",
			"Billing Province/state",
			"admin_contact_province",
			"Tech Street3",
			"Tech Street2",
			"ADMINLASTNAME",
			"zone_c",
			"Tech Street1",
			"Billing Lastname",
			"TECHPOSTALCODE",
			"Administrative Phone",
			"Tech Fax Ext",
			"Tech Fax EXT",
			"Admin Phone Number",
			"Tech Phone EXT",
			"Tech Phone Ext",
			"Tech Address2",
			"Tech Address1",
			"TECHADDRESS1",
			"Administrative State/Province",
			"TECHADDRESS2",
			"TECHADDRESS3",
			"Administrative E-mail",
			"technical_contact_fax",
			"TECHFIRSTNAME",
			"Tech ID",
			"tech_c",
			"Registrant Admin ID",
			"TECHCITY",
			"Billing Organization",
			"admin_c",
			"Admin Address",
			"Tech Name",
			"Billing Fax",
			"Billing FAX",
			"Registry Billing ID",
			"Billing Zip",
			"Administrative Country Code",
			"Billing Street1",
			"Billing Street3",
			"Billing Street2",
			"Billing Contact Information",
			"Admin PCode",
			"Billing Contact Details",
			"Admin PostalCode",
			"Admin Email",
			"Administrative, Technical, Billing Contact",
			"Admin-Name",
			"TECHEMAIL",
			"Technical Country",
			"ADMINEMAIL",
			"Billing Address",
			"BILLINGEMAIL",
			"Tech Fax Number",
			"Technical Name",
			"Admin City",
			"Technical Contact Id",
			"BILLINGCITY",
			"Tech PCode",
			"Technical Organization",
			"technical_contact_address1",
			"Billing Phone Number",
			"Tech Lastname",
			"Technical Contact",
			"Tech Address",
			"Admin Orginization",
			"Admin-Zip",
			"TECHCOUNTRY",
			"Admin CountryID",
			"Admin-State",
			"Billing Street",
			"Admin-Fax",
			"Technical Contact Information",
		},
	};
	
	public static String[] lead = {
		"Billing Contact",
		"Administrative, Technical, Billing Contact",
		"Status(es",
		"Admin-c",
		"Tech",
		"OWNER",
		"Registrant Name",
		"Billing Address",
		"Billing-c",
		"Admin Organization",
		"Tech-c",
		"Domain Servers",
		"Registrant Contact Details",
		"ADMIN",
		"Domain nameservers",
		"Domain servers in listed order",
		"Status",
		"Domain servers",
		"tech",
		"Tech contact",
		"Registrant",
		"Admin Contact",
		"Billing Contacts",
		"Admin Name",
		"technical_contact",
		"Registrant Details",
		"Registrant Street",
		"domain",
		"Administrative Contacts",
		"Tech Street",
		"registrant",
		"Technical Contact",
		"Domain Nameservers in listed order",
		"Administrative Contact Details",
		"Admin Street",
		"Domain Name Servers",
		"This domain is delegated to DynECT Managed DNS",
		"Admin contact",
		"Nameservers",
		"ns",
		"Registrant Address",
		"admin",
		"tech_c",
		"This domain is delegated to Dyn Standard DNS",
		"Registrant Contact Information",
		"Domain name servers in listed order",
		"Name Server",
		"Technical Contact Details",
		"Tech Organization",
		"Administrative Address",
		"Name Servers",
		"Administrative contact, Billing_contact, Technical contact, Zone contact",
		"Registrant contact",
		"administrative_contact",
		"Registrar",
		"Billing contact",
		"Administrative, Billing Contact",
		"Technical contact",
		"Tech Contact",
		"Tech Postal Code",
		"This domain is using Dyn Parking Service",
		"Domain status",
		"Registrant Organization",
		"Administrative Contact",
		"owner",
		"admin_c",
		"Domain Name Servers in listed order",
		"Tech Name",
		"holder",
		"Registration service provided by",
		"Administrative Contact Information",
		"Admin",
		"Name servers",
		"zone_c",
		"Domain Name servers(es",
		"Technical Address",
		"Registrant Info",
		"Owner-c",
		"Registrant Contact",
		"Technical Contact Information",
		"Administrative Contact, Technical Contact",
		"Administrative contact",
		"Billing Contact Information",
		"Billing Contact Details",
	};
	public static String[] type = {
		"Type",
	};
	public static String[] ant = {
		"Organization Name",
		"Updated",
		"Created",
		"changed",
	};
	public static String[] nil = {
		"The data in this whois database is provided to you for information",
		"DreamHost whois server terms of service: http://whois.dreamhost.com/",
		"For general domain support questions, name service and hosting issues,",
		"Domain Registry by http://www.DomainRegistry.com",
		"UNLIMITED storage, bandwidth and domains on one account. Also receive a *FREE* domain for one year when you host with http://www.hostmonster.com/",
		"Acens's WHOIS database is provided by Acens Technologies for information",
		"Register your next domain at http://www.dotEarth.com",
		"The Data in the TPP Internet Registrar WHOIS database is provided to you by",
		"You should contact DomainsNext.com for domain login/passwords,",
		"If a customer is not using our name server, the IP address of",
		"All data in this whois database is provided by dattatec.com for",
		"UNLIMITED storage, bandwidth and domains on one account. Also receive a *FREE* domain for one year when you host with http://www.bluehost.com/",
		"Uptime is the bottom line. ** Learn more here: http://dyn.com/ **",
		"The data in this whois database is provided to you for information purposes only, that is, to assist you in obtaining information about or related to a domain name registration record. We make this information available \"as is\", and do not guarantee its accuracy. By submitting a whois query, you agree that you will use this data only for lawful purposes and that, under no circumstances will you use this data to: (1) enable high volume, automated, electronic processes that stress or load this whois database system providing you this information; or (2) allow, enable, or otherwise support the transmission of mass unsolicited, commercial advertising or solicitations via direct mail, electronic mail, or by telephone. The compilation, repackaging, dissemination or other use of this data is expressly prohibited without prior written consent from us. The Registrar of record is Above.com, Pty. Ltd. We reserve the right to modify these terms at any time. By submitting this query, you agree to abide by these terms. For more information on Whois status codes, please visit https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en",
		"Get a free domain name with hosting at WEBMASTERS.COM for only $9.95 a month!",
		"APIsrs.com - http://www.apisrs.com",
		"The Data in the INTERNETTERS Registrar WHOIS database is provided to you by",
		"Web hosting company featuring affordable web and Cloud hosting,",
		"The Data in the NET4INDIA LIMITED Registrar WHOIS database is provided to you by NET4INDIA LIMITED",
		"URL of The Icann Whois data plobelms reporting system httpd://wdprs.internic.com",
		"Unlimited web hosting with free domain from only US$3.98/month.",
		"The Data in the DomainProcessor.com Registrar WHOIS database is provided to",
		"UNLIMITED storage, bandwidth and domains on one account. Also receive a *FREE* domain for one year when you host with http://www.justhost.com/",
		"# KOREAN(UTF-8)",
		"Selecting a domain name is only one part of your web site's success,",
		"Register your domain today! www.wsmdomains.com",
		"NICProxy Whois Server Ver.1.0.0",
		"Industry leading uptime since 2001! ** Learn more here: http://dyn.com/ **",
		"Java Whois Server 0.4.0.0    (c) 2006 - 2011 Klaus Zerwes zero-sys.net",
		"Support OpenSource projects by Registering your",
		"Deposez votre domaine sur le site http://www.nordnet.net",
		"The information in this whois database is provided for the sole purpose",
		"To prevent fraudulent transfers, the above domain name has been LOCKED at the registry",
		"This company may be contacted for domain login/passwords,",
		"Entre em contato conosco para quaisquer quest?es referentes a",
		"The data in this whois database is provided to you for information purposes only,",
		"The Data in the Tucows Registrar WHOIS database is provided to you by Tucows",
		"The data in this whois database is provided to you for information purposes",
		"Reseller: nicline.com's WHOIS database is only for information purposes,",
		"The data in this whois database is provided to you for information purposes only, that is,",
		"This domain's privacy is protected by contactprivacy.com. To reach the domain contacts,",
		"Now UNLIMITED Storage, UNLIMITED Bandwidth and Host UNLIMITED Domains for ONLY $4.50 per month.",
		"URL of the ICANN WHOIS Data Problem Reporting System",
	};
	public static String[] nit = {
		"record is Register4Less, Inc",
		"Query",
		"Support",
		"use",
		"purposes and that, under no circumstances will you use this data to",
		"under no circumstances will you use this data to",
		"that, under no circumstances will you use this data to",
		"record is UK2 Group Ltd",
		"WHOIS Source",
		"Domain Registration provided by",
		"Supported Extensions",
		"use this data only for lawful purposes and that, under no circumstances will you use this data to",
		"Whois Query",
		"ReadyHosting Inc",
		"NOTICE AND TERMS OF USE",
		"Query Time",
		"purposes and that, under no circumstances will you use this Data to",
		"Data only for lawful purposes and that under no circumstances will you use this Data to",
		"Registration at",
		"Accredited Registrar, contact us at",
		"About In2net, please visit",
		"by the following terms of use",
		"form at http://www.networksolutions.com/help/email.jsp with the following information",
		"under no circumstances will you use this Data to",
		"Learn more here",
		"Copy and paste the link below to view additional details",
		"record is FBS Inc",
		"Date and Time of Query",
		"data to",
		"Note",
		"iPage Inc",
		"IPOWER Inc",
		"only for lawful purposes and that, under no circumstances will you use this Data to",
		"System Status Updates",
		"NOTICE",
		"record is Reg2C.com Inc",
		"Daha fazla bilgi almak i?in info",
		"Visit",
		"will you use this data to",
		"Dispute Resolution Policy",
		"Please note",
		"By querying this server, you agree that you",
		"use this Data to",
		"and that under no circumstances will you use this Data to",
		"record is Estrategias WebSite S.L",
		"NOTE",
		"gt;&gt;&gt; Last update of WHOIS database",
		"for detailed information",
		"query, you agree to abide by the following terms of use",
		"record is NetEarth One, Inc",
		"you use this Data to",
		"For support please contact us at",
		"Unconditional Guarantee, No tricks, No gimmicks",
		"Query Source",
		"and that, under no circumstances will you use this Data to",
		"Abuse email",
		"record is Shanghai Yovole Networks, Inc",
		"Registration Service Provider",
		"circumstances will you use this data to",
		"system are expressly prohibited",
		"following terms of use",
		"lawful purposes and that, under no circumstances will you use this data to",
		"purposes and that under no circumstances will you use this Data to",
		"For complete domain details go to",
		"Reason Code",
		"You can find your provider via the following URL",
		"Last update of WHOIS database",
		"circumstances will you use this Data to",
		"URL of the ICANN WHOIS Data Problem Reporting System",
		"purpose. In addition, you agree not to",
		"mt) AccountCenter",
		"will be used for",
		"NOTICE AND TERMS OF  USE",
		"TERMS OF USE",
		"to",
		"URL into your browser",
		"will be use for",
	};
	public static String dat = "^(Created on|Updated on|Expires on|Expires On|Record updated on|Record expires on|Record created on|Record expired on|Database last updated on|Record last updated at|Record last updated on|Record last Updated on|Domain created on|Domain expires on|Last updated on).*";
}